### PR TITLE
Run delivery token before delivery api so output is only JSON

### PR DESCRIPTION
**Pull request by andy-dufour**
Fixes issue #5

### CODE REVIEW

**Comment by andy-dufour** [comment]
Tested on CentOS 6.8 and it works.

**Comment by andy-dufour** [comment]
@ncerny @stephenlauck @jeremymv2 for 👀

**Review by ncerny — APPROVED** [review]
Looks Good to me.  @jeremymv2 @itmustbejj - want to put quick eyes on this before I merge?

**Comment by ncerny** [comment]
Wait...before I merge, @andy-dufour can you update the metadata?  bump fix version.

**Comment by andy-dufour** [comment]
Version bumped

**Comment by jeremymv2** [comment]
👍

**Comment by itmustbejj** [comment]
👍

**Pull request merged**
